# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job_scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13job_scheduler.proto\x12\rjob_scheduler"\x8e\x01\n\x11SubmitJobRequest\x12\x0f\n\x07job_id\x18\x01 \x01(\t\x12\x10\n\x08job_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x13\n\x0bmax_retries\x18\x05 \x01(\x05\x12\x16\n\x0etimeout_seconds\x18\x06 \x01(\x05"E\n\x12SubmitJobResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07job_id\x18\x03 \x01(\t"\x1f\n\x12GetJobStatusRequest\x12\t\n\x01id\x18\x01 \x01(\t"\x9e\x01\n\x13GetJobStatusResponse\x12\x0f\n\x07job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x13\n\x0berror_message\x18\x04 \x01(\t\x12\x11\n\tcreated_at\x18\x05 \x01(\x03\x12\x11\n\tstarted_at\x18\x06 \x01(\x03\x12\x0f\n\x07completed_at\x18\x07 \x01(\x03\x12\x12\n\nretry_count\x18\x08 \x01(\x05"F\n\x10ListJobsRequest\x12\x14\n\x0cstatus_filter\x18\x01 \x01(\t\x12\x0e\n\x06limit\x18\x02 \x01(\x05\x12\x0c\n\x04offset\x18\x03 \x01(\x05"R\n\x11ListJobsResponse\x12\x32\n\x04jobs\x18\x01 \x03(\x0b2$.job_scheduler.GetJobStatusResponse\x12\x0f\n\x07total_count\x18\x02 \x01(\x05\x32\xd8\x01\n\x11JobSchedulerService\x12J\n\tSubmitJob\x12 .job_scheduler.SubmitJobRequest\x1a!.job_scheduler.SubmitJobResponse\x12M\n\x0cGetJobStatus\x12!.job_scheduler.GetJobStatusRequest\x1a\x1a.job_scheduler.GetJobStatusResponse\x12H\n\x08ListJobs\x12\x1f.job_scheduler.ListJobsRequest\x1a\x1b.job_scheduler.ListJobsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_scheduler_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUBMITJOBREQUEST._serialized_start=39
  _SUBMITJOBREQUEST._serialized_end=181
  _SUBMITJOBRESPONSE._serialized_start=183
  _SUBMITJOBRESPONSE._serialized_end=252
  _GETJOBSTATUSREQUEST._serialized_start=254
  _GETJOBSTATUSREQUEST._serialized_end=285
  _GETJOBSTATUSRESPONSE._serialized_start=287
  _GETJOBSTATUSRESPONSE._serialized_end=445
  _LISTJOBSREQUEST._serialized_start=447
  _LISTJOBSREQUEST._serialized_end=517
  _LISTJOBSRESPONSE._serialized_start=519
  _LISTJOBSRESPONSE._serialized_end=601
  _JOBSCHEDULERSERVICE._serialized_start=603
  _JOBSCHEDULERSERVICE._serialized_end=819

  _SUBMITJOBREQUEST._serialized_start=39
  _SUBMITJOBREQUEST._serialized_end=181
  _SUBMITJOBRESPONSE._serialized_start=183
  _SUBMITJOBRESPONSE._serialized_end=252
  _GETJOBSTATUSREQUEST._serialized_start=254
  _GETJOBSTATUSREQUEST._serialized_end=285
  _GETJOBSTATUSRESPONSE._serialized_start=287
  _GETJOBSTATUSRESPONSE._serialized_end=445
  _LISTJOBSREQUEST._serialized_start=447
  _LISTJOBSREQUEST._serialized_end=517
  _LISTJOBSRESPONSE._serialized_start=519
  _LISTJOBSRESPONSE._serialized_end=601
  _JOBSCHEDULERSERVICE._serialized_start=603
  _JOBSCHEDULERSERVICE._serialized_end=819
# @@protoc_insertion_point(module_scope)
